[cursor]
style = "Block"

[font]
size = 9

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[font.bold]
family = "Noto Sans Mono"
style = "Regular"

[window.dimensions]
columns = 64
lines = 24
