[window.dimensions]
columns = 64
lines = 24

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[font]
size = 12
normal = { family = "Terminus" }
